sudo: required
services:
  - docker

before_install:
  - docker build -t lennymanyeki/app-frontend-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lennymanyeki/app-frontend-test npm test -- --coverage

after_success:
  - docker build -t lennymanyeki/multi-client ./client
  - docker build -t lennymanyeki/multi-server ./server
  - docker build -t lennymanyeki/multi-worker ./worker
  - docker build -t lennymanyeki/multi-nginx ./nginx
  # deploy to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" -p-stdin

  - docker push lennymanyeki/multi-client
  - docker push lennymanyeki/multi-server
  - docker push lennymanyeki/multi-worker
  - docker push lennymanyeki/multi-nginx