version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'   
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
            volumes:
                - ./app/node_modules
                - ./server:/app:cached,ro
            environment:
                - REDIS_HOST=redis
                - REDIS_PORT=6379
                - PGUSER=postgres
                - PGHOST=postgres
                - PGDATABASE=postgres
                - PGPASSWORD=postgres_password
                - PGPORT=5432
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
            volumes:
                - ./client/public:/api/public:cached,ro
                - ./client/src:/api/src:cached,ro
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
            volumes:
                - ./app/node_modules
                - ./worker:/app
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3000:80'